/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package ca.ucalgary.seng301.vendingmachine.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int CONSTRUCT = 11;
  /** RegularExpression Id. */
  int CONFIGURE = 12;
  /** RegularExpression Id. */
  int EXTRACT = 13;
  /** RegularExpression Id. */
  int PRESS = 14;
  /** RegularExpression Id. */
  int INSERT = 15;
  /** RegularExpression Id. */
  int LOAD = 16;
  /** RegularExpression Id. */
  int UNLOAD = 17;
  /** RegularExpression Id. */
  int CHECK_DELIVERY = 18;
  /** RegularExpression Id. */
  int CHECK_TEARDOWN = 19;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 20;
  /** RegularExpression Id. */
  int STRING_LITERAL = 21;
  /** RegularExpression Id. */
  int LPAREN = 22;
  /** RegularExpression Id. */
  int RPAREN = 23;
  /** RegularExpression Id. */
  int COMMA = 24;
  /** RegularExpression Id. */
  int SEMICOLON = 25;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int MULTI_LINE_COMMENT = 1;
  /** Lexical state. */
  int FORMAL_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "<token of kind 10>",
    "\"construct\"",
    "\"configure\"",
    "\"extract\"",
    "\"press\"",
    "\"insert\"",
    "\"load\"",
    "\"unload\"",
    "\"CHECK_DELIVERY\"",
    "\"CHECK_TEARDOWN\"",
    "<INTEGER_LITERAL>",
    "<STRING_LITERAL>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
  };

}
